[package]
name = "rustdss"
version = "0.1.0"
authors = ["Peter East <peter@repositive.io>"]
edition = "2018"

[dependencies]
rustdss_transport = {path = "../rustdss_transport"}
rustdss_core = {path = "../rustdss_core"}
rustdss_data = {path = "../rustdss_data"}
