name: Build and test rust project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Deps
      run: |
        apt install libssl-dev
        cargo install cargo-tarpaulin
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
       cargo tarpaulin --out Xml
       bash <(curl -s https://codecov.io/bash)
    - name: Upload coveralls
