name: Build and test rust project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache cargo install
      id: precache
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('~/.cargo/bin/**') }}

    - name: Install Deps
      if: steps.precache.outputs.cache-hit != 'true'
      run: |
        sudo apt -y install libssl-dev
        cargo install cargo-tarpaulin

    - name: post Cache cargo install
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('~/.cargo/bin/**') }}

    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
